/* Generated By:JavaCC: Do not edit this line. SwiftViewsConstants.java */
package lym.languages;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SwiftViewsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRUCT = 5;
  /** RegularExpression Id. */
  int VIEW = 6;
  /** RegularExpression Id. */
  int VAR = 7;
  /** RegularExpression Id. */
  int BODY = 8;
  /** RegularExpression Id. */
  int SOME = 9;
  /** RegularExpression Id. */
  int IMAGE = 10;
  /** RegularExpression Id. */
  int TEXT = 11;
  /** RegularExpression Id. */
  int SPACER = 12;
  /** RegularExpression Id. */
  int IMPORT = 13;
  /** RegularExpression Id. */
  int SWIFTUI = 14;
  /** RegularExpression Id. */
  int VSTACK = 15;
  /** RegularExpression Id. */
  int HSTACK = 16;
  /** RegularExpression Id. */
  int OFFSET = 17;
  /** RegularExpression Id. */
  int PADDING = 18;
  /** RegularExpression Id. */
  int X = 19;
  /** RegularExpression Id. */
  int Y = 20;
  /** RegularExpression Id. */
  int TOP = 21;
  /** RegularExpression Id. */
  int BOTTOM = 22;
  /** RegularExpression Id. */
  int LEFT = 23;
  /** RegularExpression Id. */
  int RIGHT = 24;
  /** RegularExpression Id. */
  int FONT = 25;
  /** RegularExpression Id. */
  int FOREGROUNDCOLOR = 26;
  /** RegularExpression Id. */
  int UNDERSCORE = 27;
  /** RegularExpression Id. */
  int COLON = 28;
  /** RegularExpression Id. */
  int LBRACKET = 29;
  /** RegularExpression Id. */
  int RBRACKET = 30;
  /** RegularExpression Id. */
  int LPARENTHESIS = 31;
  /** RegularExpression Id. */
  int RPARENTHESIS = 32;
  /** RegularExpression Id. */
  int SIMPLEQUOTATION = 33;
  /** RegularExpression Id. */
  int DOUBLEQUOTATION = 34;
  /** RegularExpression Id. */
  int POINT = 35;
  /** RegularExpression Id. */
  int DASH = 36;
  /** RegularExpression Id. */
  int COMMA = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;
  /** RegularExpression Id. */
  int STRING = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"struct\"",
    "\"View\"",
    "\"var\"",
    "\"body\"",
    "\"some\"",
    "\"Image\"",
    "\"Text\"",
    "\"Spacer\"",
    "\"import\"",
    "\"SwiftUI\"",
    "\"VStack\"",
    "\"HStack\"",
    "\"offset\"",
    "\"padding\"",
    "\"x\"",
    "\"y\"",
    "\"top\"",
    "\"bottom\"",
    "\"left\"",
    "\"right\"",
    "\"font\"",
    "\"foregroundColor\"",
    "\"_\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\".\"",
    "\"-\"",
    "\",\"",
    "<DIGIT>",
    "<STRING>",
  };

}
