/* Generated By:JavaCC: Do not edit this line. TP1.java */
package lym.languages;

public class TP1 implements TP1Constants {
  public static void main(String args []) throws ParseException
  {
    TP1 parser = new TP1(System.in);
    while (true)
    {
      try
      {
        switch (parser.one_line())
        {
          case 0 :
          System.out.println("OK.");
          break;
          case 1 :
          System.out.println("Goodbye.");
          break;
          default :
          break;
        }
      }
      catch (Exception e)
      {
        System.out.println("NOK.");
        System.out.println(e.getMessage());
      }
      catch (Error e)
      {
        System.out.println("Oops.");
        System.out.println(e.getMessage());
        break;
      }
    }
  }

  final public int one_line() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IMPORT:
      pr();
    {if (true) return 0;}
      break;
    default:
      jj_la1[0] = jj_gen;
    {if (true) return 1;}
    }
    throw new Error("Missing return statement in function");
  }

  final public void pr() throws ParseException {
    jj_consume_token(IMPORT);
    jj_consume_token(SWIFTUI);
    label_1:
    while (true) {
      estructura();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRUCT:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
  }

  final public void estructura() throws ParseException {
    jj_consume_token(STRUCT);
    label_2:
    while (true) {
      jj_consume_token(STRING);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
    }
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(VIEW);
    jj_consume_token(LLAVESABRE);
    cuerpo();
    jj_consume_token(LLAVECIERRA);
  }

  final public void cuerpo() throws ParseException {
    jj_consume_token(VARIABLE);
    jj_consume_token(BODY);
    jj_consume_token(DOSPUNTOS);
    jj_consume_token(SOME);
    jj_consume_token(VIEW);
    jj_consume_token(LLAVESABRE);
    label_3:
    while (true) {
      contenido();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMAGEN:
      case TEXTO:
      case STACKV:
      case STACKH:
      case ESPACIO:
      case STRING:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
    }
    jj_consume_token(LLAVECIERRA);
  }

  final public void vista() throws ParseException {
    label_4:
    while (true) {
      jj_consume_token(STRING);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
    }
    jj_consume_token(PARENTESISABRE);
    jj_consume_token(PARENTESISCIERRA);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUNTO:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_5;
      }
      jj_consume_token(PUNTO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OFFSET:
        eOset();
        break;
      case PADDING:
        ePadding();
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void cTexto() throws ParseException {
    jj_consume_token(TEXTO);
    jj_consume_token(PARENTESISABRE);
    jj_consume_token(COMILLAS);
    label_6:
    while (true) {
      jj_consume_token(STRING);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_6;
      }
    }
    jj_consume_token(COMILLAS);
    jj_consume_token(PARENTESISCIERRA);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUNTO:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_7;
      }
      jj_consume_token(PUNTO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OFFSET:
        eOset();
        break;
      case PADDING:
        ePadding();
        break;
      case FONT:
        eFont();
        break;
      case FOREGROUNDCOLOR:
        eForegroundColor();
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void cImagen() throws ParseException {
    jj_consume_token(IMAGEN);
    jj_consume_token(PARENTESISABRE);
    jj_consume_token(COMILLAS);
    label_8:
    while (true) {
      jj_consume_token(STRING);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_8;
      }
    }
    jj_consume_token(COMILLAS);
    jj_consume_token(PARENTESISCIERRA);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUNTO:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_9;
      }
      jj_consume_token(PUNTO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OFFSET:
        eOset();
        break;
      case PADDING:
        ePadding();
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void cEspacio() throws ParseException {
    jj_consume_token(ESPACIO);
    jj_consume_token(PARENTESISABRE);
    jj_consume_token(PARENTESISCIERRA);
  }

  final public void componente() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TEXTO:
      cTexto();
      break;
    case IMAGEN:
      cImagen();
      break;
    case ESPACIO:
      cEspacio();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void elemento() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STACKH:
      jj_consume_token(STACKH);
      break;
    case STACKV:
      jj_consume_token(STACKV);
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(LLAVESABRE);
    label_10:
    while (true) {
      contenido();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMAGEN:
      case TEXTO:
      case STACKV:
      case STACKH:
      case ESPACIO:
      case STRING:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_10;
      }
    }
    jj_consume_token(LLAVECIERRA);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUNTO:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_11;
      }
      jj_consume_token(PUNTO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OFFSET:
        eOset();
        break;
      case PADDING:
        ePadding();
        break;
      case FONT:
        eFont();
        break;
      case FOREGROUNDCOLOR:
        eForegroundColor();
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void contenido() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
      vista();
      break;
    case IMAGEN:
    case TEXTO:
    case ESPACIO:
      componente();
      break;
    case STACKV:
    case STACKH:
      elemento();
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void eOset() throws ParseException {
    jj_consume_token(OFFSET);
    jj_consume_token(PARENTESISABRE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case XVA:
    case YVA:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case XVA:
        jj_consume_token(XVA);
        jj_consume_token(DOSPUNTOS);
        jj_consume_token(DIGITO);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMA:
          jj_consume_token(COMA);
          jj_consume_token(YVA);
          jj_consume_token(DOSPUNTOS);
          jj_consume_token(DIGITO);
          break;
        default:
          jj_la1[19] = jj_gen;
          ;
        }
        break;
      case YVA:
        jj_consume_token(YVA);
        jj_consume_token(DOSPUNTOS);
        jj_consume_token(DIGITO);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMA:
          jj_consume_token(COMA);
          jj_consume_token(XVA);
          jj_consume_token(DOSPUNTOS);
          jj_consume_token(DIGITO);
          break;
        default:
          jj_la1[20] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[22] = jj_gen;
      ;
    }
    jj_consume_token(PARENTESISCIERRA);
  }

  final public void ePadding() throws ParseException {
    jj_consume_token(PADDING);
    jj_consume_token(PARENTESISABRE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PUNTO:
      jj_consume_token(PUNTO);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TOP:
        jj_consume_token(TOP);
        break;
      case BOTTOM:
        jj_consume_token(BOTTOM);
        break;
      case LEFT:
        jj_consume_token(LEFT);
        break;
      case RIGHT:
        jj_consume_token(RIGHT);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(COMA);
      jj_consume_token(DIGITO);
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    jj_consume_token(PARENTESISCIERRA);
  }

  final public void eFont() throws ParseException {
    jj_consume_token(FONT);
    jj_consume_token(PARENTESISABRE);
    jj_consume_token(PUNTO);
    label_12:
    while (true) {
      jj_consume_token(STRING);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_12;
      }
    }
    jj_consume_token(PARENTESISCIERRA);
  }

  final public void eForegroundColor() throws ParseException {
    jj_consume_token(FOREGROUNDCOLOR);
    jj_consume_token(PARENTESISABRE);
    jj_consume_token(PUNTO);
    label_13:
    while (true) {
      jj_consume_token(STRING);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING:
        ;
        break;
      default:
        jj_la1[26] = jj_gen;
        break label_13;
      }
    }
    jj_consume_token(PARENTESISCIERRA);
  }

  /** Generated Token Manager. */
  public TP1TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[27];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x20,0x80,0x0,0x3c0000,0x0,0x20000,0xc00000,0x0,0x20000,0x5c00000,0x0,0x20000,0xc00000,0xc0000,0x300000,0x3c0000,0x20000,0x5c00000,0x3c0000,0x0,0x0,0x18000000,0x18000000,0xe0000000,0x20000,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x4,0x6,0x4,0x0,0x0,0x4,0x0,0x0,0x4,0x0,0x0,0x2,0x0,0x6,0x0,0x0,0x6,0x8,0x8,0x0,0x0,0x1,0x0,0x4,0x4,};
   }

  /** Constructor with InputStream. */
  public TP1(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public TP1(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new TP1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public TP1(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new TP1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public TP1(TP1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(TP1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[38];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 27; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 38; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
