/* Generated By:JavaCC: Do not edit this line. TP1Constants.java */
package lym.languages;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TP1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPORT = 5;
  /** RegularExpression Id. */
  int SWIFTUI = 6;
  /** RegularExpression Id. */
  int STRUCT = 7;
  /** RegularExpression Id. */
  int VIEW = 8;
  /** RegularExpression Id. */
  int LLAVESABRE = 9;
  /** RegularExpression Id. */
  int LLAVECIERRA = 10;
  /** RegularExpression Id. */
  int PARENTESISABRE = 11;
  /** RegularExpression Id. */
  int PARENTESISCIERRA = 12;
  /** RegularExpression Id. */
  int VARIABLE = 13;
  /** RegularExpression Id. */
  int BODY = 14;
  /** RegularExpression Id. */
  int SOME = 15;
  /** RegularExpression Id. */
  int COMILLAS = 16;
  /** RegularExpression Id. */
  int PUNTO = 17;
  /** RegularExpression Id. */
  int IMAGEN = 18;
  /** RegularExpression Id. */
  int TEXTO = 19;
  /** RegularExpression Id. */
  int STACKV = 20;
  /** RegularExpression Id. */
  int STACKH = 21;
  /** RegularExpression Id. */
  int OFFSET = 22;
  /** RegularExpression Id. */
  int PADDING = 23;
  /** RegularExpression Id. */
  int FONT = 24;
  /** RegularExpression Id. */
  int DOSPUNTOS = 25;
  /** RegularExpression Id. */
  int FOREGROUNDCOLOR = 26;
  /** RegularExpression Id. */
  int XVA = 27;
  /** RegularExpression Id. */
  int YVA = 28;
  /** RegularExpression Id. */
  int TOP = 29;
  /** RegularExpression Id. */
  int BOTTOM = 30;
  /** RegularExpression Id. */
  int LEFT = 31;
  /** RegularExpression Id. */
  int RIGHT = 32;
  /** RegularExpression Id. */
  int ESPACIO = 33;
  /** RegularExpression Id. */
  int STRING = 34;
  /** RegularExpression Id. */
  int COMA = 35;
  /** RegularExpression Id. */
  int MENOS = 36;
  /** RegularExpression Id. */
  int DIGITO = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"import\"",
    "\"SwiftUI\"",
    "\"struct\"",
    "\"View\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"var\"",
    "\"body\"",
    "\"some\"",
    "\"\\\"\"",
    "\".\"",
    "\"Image\"",
    "\"Text\"",
    "\"VStack\"",
    "\"HStack\"",
    "\"offset\"",
    "\"padding\"",
    "\"font\"",
    "\":\"",
    "\"foregroundColor\"",
    "\"x\"",
    "\"y\"",
    "\"top\"",
    "\"bottom\"",
    "\"left\"",
    "\"right\"",
    "\"Spacer\"",
    "<STRING>",
    "\",\"",
    "\"-\"",
    "<DIGITO>",
  };

}
